[project]
name = "md-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.19.1",
    "ruff>=0.14.10",
    "mdformat>=0.7.17",
]
